export const FETCH_FLIGHTS = "FETCH_FLIGHTS";
export const LOGIN_AUTH_SUCCESS = "LOGIN_AUTH_SUCCESS";
export const LOGIN_AUTH_FAILURE = "LOGIN_AUTH_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const SESSION_LOGIN_SUCCESS = "SESSION_LOGIN_SUCCESS";
export const SESSION_LOGIN_FAILURE = "SESSION_LOGIN_FAILURE";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";